---
 - name: Creating list of users in chennai datacenter
   hosts: chennai
   vars_files:
    - variables/users.yml
   tasks:

    - name: Create user
      user:
        name: "{{item}}"
        state: present
      loop: "{{users}}"
...
